### Logistic Regression Implementation 
- on synthetically generated data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

RANDOM_STATE = 15

In [2]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1200, n_features=9, n_classes=2, random_state=RANDOM_STATE)

In [3]:
df = pd.DataFrame(X, columns=[f'feature{i}' for i in range(1, 10)])

df['target'] = y

In [4]:
df.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,target
0,-0.678084,-1.168784,-0.396585,-0.750901,0.318124,-0.214755,0.713357,-1.965636,0.724709,0
1,1.273290,1.168108,0.248769,0.703696,-1.379711,-0.534346,-1.105935,0.656240,0.978545,1
2,1.286952,0.609599,-0.828121,0.726689,-0.806056,0.447817,-0.608994,-0.753998,0.648640,1
3,0.504017,0.865311,0.008795,-2.290390,0.076449,-1.239904,-0.412666,0.197809,-1.036871,1
4,0.995913,2.121625,0.949027,0.755207,-2.610291,0.478512,-2.047316,0.321279,1.944647,1

In [5]:
X = df.iloc[:, :-1]
X

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9
0,-0.678084,-1.168784,-0.396585,-0.750901,0.318124,-0.214755,0.713357,-1.965636,0.724709
1,1.273290,1.168108,0.248769,0.703696,-1.379711,-0.534346,-1.105935,0.656240,0.978545
2,1.286952,0.609599,-0.828121,0.726689,-0.806056,0.447817,-0.608994,-0.753998,0.648640
3,0.504017,0.865311,0.008795,-2.290390,0.076449,-1.239904,-0.412666,0.197809,-1.036871
4,0.995913,2.121625,0.949027,0.755207,-2.610291,0.478512,-2.047316,0.321279,1.944647
...,...,...,...,...,...,...,...,...,...
1195,-0.821371,0.787249,0.908182,0.188496,-1.197456,1.175213,-0.844392,-0.364134,1.088655
1196,-1.289123,1.530549,-1.007069,-2.284822,-1.758207,-1.118845,-1.430726,-1.091654,1.202619
1197,1.379029,1.256367,-0.406451,1.985111,-0.432469,0.474312,-0.800311,1.189936,-0.633864
1198,1.202351,1.443892,-2.207257,0.209109,-0.708097,0.193385,-0.997891,-1.411072,-0.389956
1199,0.201269,-1.732502,-0.354454,0.811172,1.786494,0.538402,1.544110,0.512735,-1.034605

In [6]:
y = df.iloc[:, -1]
y

0       0
1       1
2       1
3       1
4       1
       ..
1195    1
1196    1
1197    1
1198    1
1199    0
Name: target, Length: 1200, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=RANDOM_STATE)

In [8]:
print(f"X_train Shape: {X_train.shape}")
print(f"X_test Shape: {X_test.shape}")

X_train Shape: (900, 9)
X_test Shape: (300, 9)

In [9]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()
logistic.fit(X_train, y_train)

LogisticRegression()

#### Why not fit_tranform() X_test?
Since make_classification generates data that is already fairly normalized, you might not notice a big difference here, but in real-world data, skipping scaling with Logistic Regression can seriously hurt performance.

In [10]:
y_pred = logistic.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

score=accuracy_score(y_test, y_pred)
print("Accuracy Score =", score)
print("\n")
print("Classification Report:\n", classification_report(y_test ,y_pred))
print("Confusion Matrix:\n" ,confusion_matrix(y_test, y_pred))

Accuracy Score = 0.9233333333333333


Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.89      0.92       147
           1       0.90      0.95      0.93       153

    accuracy                           0.92       300
   macro avg       0.93      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

Confusion Matrix:
 [[131  16]
 [  7 146]]

#### Hyperparameter Tuning and Crossvalidation

GridSearchCV

In [12]:
model = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c_values = [100, 10, 1, 0.1, 0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [13]:
params = dict(penalty=penalty, C=c_values, solver=solver)

In [14]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [15]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold()

In [16]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(estimator=model,
                   param_grid=params,
                   scoring='accuracy',
                   cv=cv,
                   n_jobs=-1)

In [17]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [18]:
grid.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [19]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'liblinear'}

In [20]:
grid.best_score_

np.float64(0.9133333333333333)

In [21]:
y_pred2 = grid.predict(X_test)

In [22]:
score = accuracy_score(y_test, y_pred2)
print("Accuracy Score =", score)
print("Classification Score:\n", classification_report(y_test, y_pred2))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred2))

Accuracy Score = 0.9266666666666666
Classification Score:
               precision    recall  f1-score   support

           0       0.95      0.90      0.92       147
           1       0.91      0.95      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300

Confusion Matrix:
 [[132  15]
 [  7 146]]

- Randomized Search CV

In [23]:
from sklearn.model_selection import RandomizedSearchCV

randomcv=RandomizedSearchCV(estimator=model, param_distributions=params, cv=5, scoring='accuracy')

In [24]:
randomcv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [25]:
randomcv.best_score_

np.float64(0.9133333333333333)

In [26]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 10}

In [27]:
y_pred3=randomcv.predict(X_test)

In [28]:
score = accuracy_score(y_test, y_pred3)
print("Accuracy Score =", score)
print("Classification Score:\n", classification_report(y_test, y_pred3))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred3))

Accuracy Score = 0.9266666666666666
Classification Score:
               precision    recall  f1-score   support

           0       0.95      0.90      0.92       147
           1       0.91      0.95      0.93       153

    accuracy                           0.93       300
   macro avg       0.93      0.93      0.93       300
weighted avg       0.93      0.93      0.93       300

Confusion Matrix:
 [[132  15]
 [  7 146]]

#### Logistic Regression for multiclass classification

In [29]:
X, y = make_classification(n_samples=1000, n_features=10, n_informative=3, n_classes=3, random_state=15)

In [30]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7,8,9
0,-1.286132,-0.648334,1.044115,-0.469715,0.789859,-0.083727,-1.647309,-1.316412,1.011910,-0.898063
1,-0.222224,2.083232,1.191114,-1.354527,-0.956992,1.696028,-1.070406,0.981403,-1.628798,1.377594
2,-0.431963,0.375745,-1.370334,0.819214,0.345243,1.389447,-1.904130,1.292602,0.925545,0.232705
3,-0.912633,0.986988,-0.690042,2.014628,-0.442260,0.590347,-1.819353,1.560938,0.823755,0.517762
4,-0.367056,1.667892,0.879172,2.214276,1.846338,-0.894047,1.543838,0.931103,-1.015210,1.061845

In [31]:
X_train, X_test, y_train, y_test=train_test_split(X, y,
                                               test_size=0.25,
                                               random_state=42)

In [32]:
from sklearn.multiclass import OneVsRestClassifier

model = OneVsRestClassifier(LogisticRegression())

In [33]:
model.fit(X_train, y_train)

OneVsRestClassifier(estimator=LogisticRegression())

In [34]:
model.n_features_in_

10

In [35]:
model.classes_

array([0, 1, 2])

In [36]:
model.decision_function(X_train)

array([[-4.26553504, -0.46226358, -0.11938499],
       [ 0.15574673, -1.40267761, -2.6202539 ],
       [-3.93247612, -1.35173612,  0.62461383],
       ...,
       [-3.63681147,  0.69218834, -1.35843087],
       [-2.18433201,  1.13231733, -2.87682988],
       [-3.15784906, -4.32331784,  2.27143926]], shape=(750, 3))

In [37]:
model.get_params()

{'estimator__C': 1.0,
 'estimator__class_weight': None,
 'estimator__dual': False,
 'estimator__fit_intercept': True,
 'estimator__intercept_scaling': 1,
 'estimator__l1_ratio': None,
 'estimator__max_iter': 100,
 'estimator__multi_class': 'deprecated',
 'estimator__n_jobs': None,
 'estimator__penalty': 'l2',
 'estimator__random_state': None,
 'estimator__solver': 'lbfgs',
 'estimator__tol': 0.0001,
 'estimator__verbose': 0,
 'estimator__warm_start': False,
 'estimator': LogisticRegression(),
 'n_jobs': None,
 'verbose': 0}

In [38]:
y_pred = model.predict(X_test)

In [39]:
y_pred

array([2, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 1, 0, 2, 0, 1,
       2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2,
       0, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 2, 0, 0, 2, 2, 2])

In [40]:
model.predict_proba(X_test)

array([[1.13073983e-04, 1.78835287e-01, 8.21051639e-01],
       [2.21334448e-01, 6.57396598e-01, 1.21268954e-01],
       [4.80356728e-06, 2.53640459e-01, 7.46354738e-01],
       [1.19201764e-01, 8.16095016e-01, 6.47032204e-02],
       [9.45172038e-02, 8.82178871e-01, 2.33039252e-02],
       [8.57121413e-01, 4.40329884e-02, 9.88455987e-02],
       [7.97649510e-01, 6.66904393e-02, 1.35660051e-01],
       [9.23368796e-01, 2.05387213e-02, 5.60924827e-02],
       [4.00499171e-02, 3.68333115e-01, 5.91616968e-01],
       [7.94802216e-01, 1.96195490e-01, 9.00229364e-03],
       [7.15358557e-04, 3.44551779e-01, 6.54732862e-01],
       [3.44680668e-01, 5.86354329e-01, 6.89650032e-02],
       [1.45750340e-01, 5.48482176e-03, 8.48764838e-01],
       [2.61142736e-02, 4.20634587e-01, 5.53251140e-01],
       [9.06817799e-03, 3.68351785e-01, 6.22580037e-01],
       [2.87885535e-02, 3.84259243e-02, 9.32785522e-01],
       [1.05826656e-02, 1.62039325e-01, 8.27378009e-01],
       [6.70825079e-01, 3.19625106e-01, 9.54981517e-03],
       [9.15177545e-01, 4.41617645e-02, 4.06606908e-02],
       [4.49068214e-01, 7.22240960e-03, 5.43709376e-01],
       [2.37304441e-01, 1.70696794e-02, 7.45625879e-01],
       [1.70385837e-01, 7.84490317e-01, 4.51238461e-02],
       [2.25472036e-01, 7.14100471e-01, 6.04274929e-02],
       [7.86897882e-02, 8.19004355e-01, 1.02305857e-01],
       [1.48001430e-01, 8.08801263e-01, 4.31973072e-02],
       [5.09870774e-01, 1.85147418e-01, 3.04981808e-01],
       [8.16497131e-01, 1.31927914e-01, 5.15749543e-02],
       [3.84815503e-01, 2.94887243e-01, 3.20297254e-01],
       [1.70994605e-01, 2.92781091e-02, 7.99727286e-01],
       [3.60558761e-01, 6.17750831e-01, 2.16904076e-02],
       [6.66157455e-01, 3.26976998e-01, 6.86554649e-03],
       [9.38091434e-02, 2.93246180e-01, 6.12944676e-01],
       [2.52056571e-04, 3.60613366e-01, 6.39134578e-01],
       [3.00379227e-01, 6.98856057e-01, 7.64716701e-04],
       [1.18133245e-03, 3.85941754e-01, 6.12876913e-01],
       [8.49820154e-01, 5.46802194e-02, 9.54996262e-02],
       [6.40863869e-01, 2.06105308e-01, 1.53030823e-01],
       [5.14291883e-03, 1.76252259e-01, 8.18604822e-01],
       [1.90104180e-01, 4.20435097e-03, 8.05691469e-01],
       [2.26452165e-02, 8.23552107e-01, 1.53802676e-01],
       [2.05265893e-02, 1.26154517e-01, 8.53318893e-01],
       [4.95247326e-02, 9.80687487e-02, 8.52406519e-01],
       [7.88340249e-04, 8.04902569e-02, 9.18721403e-01],
       [8.89664064e-02, 6.48811966e-01, 2.62221627e-01],
       [2.54210435e-01, 5.02212825e-03, 7.40767436e-01],
       [5.95390724e-01, 3.93518293e-01, 1.10909825e-02],
       [9.62445966e-02, 8.43756158e-01, 5.99992450e-02],
       [9.35802080e-04, 1.98624588e-01, 8.00439610e-01],
       [8.04592409e-01, 4.53113163e-02, 1.50096275e-01],
       [8.49344680e-02, 8.14781428e-01, 1.00284104e-01],
       [7.77534949e-01, 1.39983921e-01, 8.24811306e-02],
       [5.10788911e-01, 1.32352818e-01, 3.56858271e-01],
       [8.83783781e-01, 5.89904894e-02, 5.72257300e-02],
       [1.53210794e-01, 8.42743229e-01, 4.04597649e-03],
       [2.17571133e-01, 7.67682767e-01, 1.47460992e-02],
       [2.18921841e-03, 4.26713792e-01, 5.71096989e-01],
       [6.27835642e-01, 2.00608722e-01, 1.71555636e-01],
       [9.82637991e-01, 1.16138499e-02, 5.74815872e-03],
       [3.77060207e-02, 9.04567089e-01, 5.77268902e-02],
       [1.90355584e-01, 6.65748668e-01, 1.43895748e-01],
       [7.46323360e-01, 2.52152251e-01, 1.52438897e-03],
       [1.13898986e-01, 8.05880186e-01, 8.02208276e-02],
       [7.03911870e-01, 2.95098823e-01, 9.89307410e-04],
       [4.04400626e-01, 5.93292486e-01, 2.30688842e-03],
       [2.84969499e-01, 5.45929991e-01, 1.69100511e-01],
       [5.23183496e-01, 4.41818471e-01, 3.49980329e-02],
       [1.45926035e-04, 1.92690568e-01, 8.07163506e-01],
       [1.04546655e-01, 8.31630917e-01, 6.38224275e-02],
       [6.96860176e-01, 2.94978496e-01, 8.16132778e-03],
       [1.73795825e-01, 7.59330358e-01, 6.68738170e-02],
       [9.31979156e-01, 4.44150443e-02, 2.36058000e-02],
       [4.85590477e-02, 8.14391269e-01, 1.37049683e-01],
       [1.57731808e-02, 1.28117195e-01, 8.56109624e-01],
       [1.38701518e-01, 8.20444376e-01, 4.08541060e-02],
       [4.66376910e-02, 1.69374322e-01, 7.83987987e-01],
       [1.61013765e-02, 4.06875259e-01, 5.77023365e-01],
       [1.16901483e-01, 7.20340803e-01, 1.62757715e-01],
       [5.47740274e-01, 2.88036110e-03, 4.49379365e-01],
       [2.22772836e-01, 5.60227932e-01, 2.16999232e-01],
       [5.59900437e-01, 1.29286423e-03, 4.38806698e-01],
       [8.85344344e-02, 8.01764059e-01, 1.09701506e-01],
       [8.86344000e-01, 8.53776896e-02, 2.82783106e-02],
       [6.16305490e-02, 6.77439607e-01, 2.60929844e-01],
       [2.20655920e-02, 3.68164181e-01, 6.09770227e-01],
       [2.02121529e-05, 2.42589471e-01, 7.57390317e-01],
       [5.33075749e-01, 3.81053060e-04, 4.66543198e-01],
       [1.39615397e-02, 8.16834843e-01, 1.69203617e-01],
       [2.18183535e-02, 1.06008064e-01, 8.72173582e-01],
       [1.89620096e-03, 9.90596016e-02, 8.99044197e-01],
       [1.10388630e-01, 7.75897710e-01, 1.13713660e-01],
       [4.59238944e-02, 6.26788592e-01, 3.27287514e-01],
       [1.11005154e-04, 1.06229419e-01, 8.93659576e-01],
       [5.57959039e-06, 9.35940893e-02, 9.06400331e-01],
       [7.60610649e-01, 1.81263700e-01, 5.81256513e-02],
       [8.46141774e-01, 1.17806983e-01, 3.60512430e-02],
       [8.13452462e-01, 1.40501462e-01, 4.60460763e-02],
       [5.81708648e-02, 3.88440557e-01, 5.53388579e-01],
       [2.55312176e-02, 3.04813407e-01, 6.69655376e-01],
       [9.31678520e-01, 4.11488208e-02, 2.71726596e-02],
       [3.53019310e-02, 5.27127294e-01, 4.37570775e-01],
       [2.02200358e-02, 9.76973944e-02, 8.82082570e-01],
       [9.16571840e-02, 6.71437409e-01, 2.36905407e-01],
       [4.32077289e-01, 1.52599936e-02, 5.52662717e-01],
       [2.92871410e-01, 7.06509166e-01, 6.19424186e-04],
       [8.86568161e-01, 8.35117799e-02, 2.99200586e-02],
       [1.52243918e-01, 4.42505616e-01, 4.05250466e-01],
       [5.69865800e-01, 2.15692268e-01, 2.14441933e-01],
       [5.27066580e-02, 9.72698235e-03, 9.37566360e-01],
       [7.23907760e-01, 2.72106690e-01, 3.98555028e-03],
       [7.98753621e-02, 9.13019979e-01, 7.10465874e-03],
       [2.05798062e-01, 3.94050378e-01, 4.00151560e-01],
       [1.88350207e-01, 8.08361002e-01, 3.28879170e-03],
       [5.20617784e-02, 1.59406778e-02, 9.31997544e-01],
       [5.44349260e-06, 2.03236671e-01, 7.96757885e-01],
       [6.85085888e-02, 8.71359425e-01, 6.01319861e-02],
       [1.29970885e-01, 8.36380618e-01, 3.36484969e-02],
       [5.63780581e-02, 9.32593095e-01, 1.10288466e-02],
       [1.38679850e-01, 6.89552946e-01, 1.71767203e-01],
       [5.83000217e-05, 1.65401523e-01, 8.34540177e-01],
       [7.65281722e-01, 2.01517110e-01, 3.32011678e-02],
       [1.64778121e-04, 2.02900743e-01, 7.96934479e-01],
       [5.79177775e-01, 3.89620378e-01, 3.12018463e-02],
       [8.59586849e-02, 8.11249891e-01, 1.02791425e-01],
       [2.44559756e-04, 1.31450229e-01, 8.68305211e-01],
       [9.34705206e-01, 1.37959220e-02, 5.14988718e-02],
       [6.40241910e-01, 3.52627748e-01, 7.13034173e-03],
       [3.25395469e-01, 2.67313659e-01, 4.07290872e-01],
       [3.33699072e-01, 1.58747412e-01, 5.07553516e-01],
       [7.74348618e-06, 3.19532853e-01, 6.80459403e-01],
       [3.37303792e-01, 5.69875409e-01, 9.28207989e-02],
       [2.87752969e-02, 9.33883002e-02, 8.77836403e-01],
       [8.04658916e-01, 4.04392630e-02, 1.54901821e-01],
       [3.36238463e-01, 1.31666611e-01, 5.32094926e-01],
       [7.37983743e-02, 1.24943375e-03, 9.24952192e-01],
       [8.48313390e-01, 1.26789256e-01, 2.48973537e-02],
       [9.00115344e-01, 2.12529917e-03, 9.77593568e-02],
       [6.65612539e-01, 2.64862637e-01, 6.95248239e-02],
       [8.09997102e-03, 9.74423709e-02, 8.94457658e-01],
       [8.59325240e-01, 1.01286480e-01, 3.93882791e-02],
       [9.58084214e-03, 1.50781340e-01, 8.39637818e-01],
       [8.78452181e-01, 4.92414064e-02, 7.23064122e-02],
       [2.38518631e-01, 7.58910182e-01, 2.57118630e-03],
       [3.75204698e-01, 2.99032203e-02, 5.94892081e-01],
       [2.99794290e-02, 5.28716812e-01, 4.41303759e-01],
       [1.18347522e-02, 8.72646508e-01, 1.15518740e-01],
       [2.21382425e-01, 3.27062215e-01, 4.51555360e-01],
       [8.02794168e-01, 1.30787136e-01, 6.64186955e-02],
       [9.39821221e-01, 4.49120434e-02, 1.52667354e-02],
       [4.31578240e-02, 8.78539542e-01, 7.83026341e-02],
       [8.25992446e-02, 7.75152682e-01, 1.42248074e-01],
       [4.71347577e-02, 2.88479345e-02, 9.24017308e-01],
       [2.43554261e-02, 9.75611283e-03, 9.65888461e-01],
       [1.06514208e-03, 3.18798098e-01, 6.80136760e-01],
       [3.79619292e-02, 8.43870793e-01, 1.18167278e-01],
       [4.97749670e-02, 1.96520325e-01, 7.53704708e-01],
       [9.69149611e-01, 1.99094516e-02, 1.09409374e-02],
       [1.68853323e-03, 2.07684323e-01, 7.90627143e-01],
       [9.22465515e-02, 2.25034998e-02, 8.85249949e-01],
       [6.28804484e-03, 2.76687957e-01, 7.17023998e-01],
       [1.61504483e-01, 8.31919538e-01, 6.57597826e-03],
       [7.93722078e-01, 1.79198315e-01, 2.70796073e-02],
       [1.24846279e-02, 4.81597961e-02, 9.39355576e-01],
       [5.35935833e-01, 3.93839029e-01, 7.02251380e-02],
       [6.99459805e-01, 3.00190929e-01, 3.49265554e-04],
       [1.23145051e-01, 1.10963529e-01, 7.65891420e-01],
       [8.02984057e-01, 6.15308626e-02, 1.35485081e-01],
       [8.82889779e-06, 2.17479741e-01, 7.82511430e-01],
       [6.97652465e-01, 1.84177189e-01, 1.18170346e-01],
       [8.61197842e-01, 5.86710533e-02, 8.01311046e-02],
       [3.41036401e-01, 5.94382838e-01, 6.45807613e-02],
       [6.88896739e-02, 2.11996015e-02, 9.09910725e-01],
       [8.93801110e-01, 8.69574583e-02, 1.92414322e-02],
       [4.04087740e-01, 5.83503061e-01, 1.24091987e-02],
       [3.55330269e-01, 6.42019597e-01, 2.65013430e-03],
       [1.84202449e-01, 8.11555432e-01, 4.24211948e-03],
       [2.14160350e-01, 4.37392746e-01, 3.48446904e-01],
       [8.70121954e-01, 9.22149187e-03, 1.20656555e-01],
       [4.00185314e-01, 7.89725181e-02, 5.20842168e-01],
       [8.16876516e-02, 8.15768354e-01, 1.02543994e-01],
       [5.75123644e-01, 4.05855838e-01, 1.90205179e-02],
       [4.62916911e-01, 2.10358057e-01, 3.26725033e-01],
       [1.09881191e-01, 8.63345409e-01, 2.67733991e-02],
       [7.42483761e-02, 1.56611687e-02, 9.10090455e-01],
       [1.20811623e-04, 2.97331867e-01, 7.02547322e-01],
       [2.43606978e-02, 3.92149139e-02, 9.36424388e-01],
       [7.90678080e-06, 2.63333981e-01, 7.36658113e-01],
       [1.24011150e-01, 2.16268972e-03, 8.73826160e-01],
       [5.02408369e-01, 2.39654109e-02, 4.73626220e-01],
       [7.83651353e-02, 8.25287817e-01, 9.63470479e-02],
       [5.98869856e-02, 8.64780921e-01, 7.53320933e-02],
       [3.22540857e-01, 1.81195796e-01, 4.96263347e-01],
       [2.16566092e-03, 3.66729310e-01, 6.31105029e-01],
       [1.13239173e-02, 5.32486800e-01, 4.56189282e-01],
       [2.96271762e-01, 1.78327105e-01, 5.25401132e-01],
       [2.78293204e-02, 1.06287044e-01, 8.65883636e-01],
       [1.82540737e-02, 3.17498793e-01, 6.64247134e-01],
       [1.54894551e-01, 2.76644159e-01, 5.68461290e-01],
       [6.00551579e-02, 4.61859497e-01, 4.78085345e-01],
       [5.93704653e-01, 3.01547098e-01, 1.04748248e-01],
       [5.87746912e-01, 3.29853072e-01, 8.24000164e-02],
       [3.17272155e-01, 6.81734668e-01, 9.93176976e-04],
       [2.13312552e-01, 4.47082751e-02, 7.41979173e-01],
       [1.99463072e-01, 2.68870062e-02, 7.73649922e-01],
       [7.45286934e-01, 1.82096952e-01, 7.26161133e-02],
       [9.15261954e-01, 8.23639388e-02, 2.37410694e-03],
       [4.06161821e-01, 2.47389695e-02, 5.69099210e-01],
       [3.12477837e-02, 8.94566954e-01, 7.41852623e-02],
       [4.83500948e-02, 2.51724993e-01, 6.99924912e-01],
       [1.97622887e-01, 8.00035066e-01, 2.34204689e-03],
       [9.03758963e-01, 6.07183309e-02, 3.55227057e-02],
       [7.44197257e-01, 2.13294806e-01, 4.25079371e-02],
       [2.87818938e-01, 2.10272058e-01, 5.01909005e-01],
       [1.07053303e-01, 7.25277568e-01, 1.67669129e-01],
       [1.47694150e-01, 7.34745417e-01, 1.17560433e-01],
       [9.77862111e-02, 8.65662590e-01, 3.65511992e-02],
       [7.91122231e-02, 2.26146288e-01, 6.94741489e-01],
       [5.16747746e-06, 2.21429299e-01, 7.78565534e-01],
       [1.77617167e-01, 7.96889122e-01, 2.54937113e-02],
       [2.05523755e-02, 3.94829719e-02, 9.39964653e-01],
       [1.52695883e-01, 8.41441311e-01, 5.86280613e-03],
       [9.76030132e-01, 5.20629504e-03, 1.87635729e-02],
       [9.30446246e-02, 8.20164422e-01, 8.67909532e-02],
       [5.75047920e-01, 3.54504049e-01, 7.04480311e-02],
       [9.31969745e-01, 4.43391661e-02, 2.36910892e-02],
       [3.53357189e-01, 6.18606143e-01, 2.80366678e-02],
       [7.70618732e-01, 1.79512585e-01, 4.98686830e-02],
       [3.18211696e-02, 5.37021735e-02, 9.14476657e-01],
       [2.42192652e-01, 6.28588528e-01, 1.29218820e-01],
       [7.04219763e-01, 2.74333975e-01, 2.14462620e-02],
       [1.30807096e-01, 3.34961387e-01, 5.34231517e-01],
       [5.27728203e-04, 3.48454582e-01, 6.51017689e-01],
       [3.85594580e-01, 4.65701134e-01, 1.48704287e-01],
       [2.95961534e-01, 6.61649527e-01, 4.23889388e-02],
       [2.63878527e-01, 7.27063668e-01, 9.05780481e-03],
       [3.63741750e-01, 2.23925299e-01, 4.12332951e-01],
       [3.24762824e-01, 5.19342277e-01, 1.55894899e-01],
       [5.49265841e-02, 7.32932766e-01, 2.12140650e-01],
       [8.06219201e-01, 1.64875932e-01, 2.89048667e-02],
       [7.60002790e-02, 6.63357172e-01, 2.60642549e-01],
       [1.66981464e-01, 8.20155878e-01, 1.28626576e-02],
       [8.29903622e-01, 1.47891682e-01, 2.22046956e-02],
       [8.65287733e-01, 1.14041484e-01, 2.06707829e-02],
       [8.62950276e-01, 1.13211568e-01, 2.38381561e-02],
       [6.60557718e-01, 2.95763924e-01, 4.36783581e-02],
       [7.22002082e-03, 2.54685104e-02, 9.67311469e-01],
       [5.74371778e-01, 4.12558224e-01, 1.30699985e-02],
       [7.72087443e-01, 1.48577915e-01, 7.93346423e-02],
       [3.46279444e-02, 4.69517987e-02, 9.18420257e-01],
       [1.83139355e-03, 2.60998775e-01, 7.37169832e-01],
       [4.65122572e-01, 3.67846759e-03, 5.31198960e-01]])

In [41]:
score = accuracy_score(y_test, y_pred)
print("Accuracy Score =", score)
print("Classification Score:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy Score = 0.788
Classification Score:
               precision    recall  f1-score   support

           0       0.84      0.83      0.84        78
           1       0.84      0.73      0.78        91
           2       0.70      0.81      0.75        81

    accuracy                           0.79       250
   macro avg       0.79      0.79      0.79       250
weighted avg       0.79      0.79      0.79       250

Confusion Matrix:
 [[65  7  6]
 [ 3 66 22]
 [ 9  6 66]]